### ISSUE TITLE
Is it possible to manage a list of users?

### ISSUE THREAD

**Issue by alexandre-mbm** [getgrav/grav-plugin-login-oauth#6]
I would want to have just more two authors. Friends. The OAuth would ease with passwords.

**Comment by Vivalldi** [comment]
Managing users via a GUI is not possible, no (more on that in Admin Pro). In order to change permissions of OAuth users you would need to have them create an account on your site with OAuth and then find the files in `users/accounts/someusername` (i don't remember the naming convention of OAuth) and edit their access. 

Side note, OAuth is currently not supported in the admin plugin, where most people would write content.

**Comment by alexandre-mbm** [comment]
1. Can not an OAuth user use the admin plugin?
2. Can not an OAuth user use password (optionally)?
3. Can not an OAuth user from more that one service?

**Comment by Vivalldi** [comment]
1. An OAuth user is unable to use the admin plugin (the admin plugin handles authorization separately).
2. An OAuth user cannot use a password (as the "password" is set based on some user metrics provided by OAuth
3. Currently OAuth accounts do not link to each other

**Comment by alexandre-mbm** [comment]
What is the use to be an OAuth user? What can it to do?

In another services, I can be a simple user with OAuth credentials associated to my account. So I have OAuth and local password for a unique username.

**Comment by Vivalldi** [comment]
Currently an OAuth user is able to access front-end pages that have permission based access restrictions. Linking OAuth and normal user logins is a feature that we could look into. Access to the admin panel can be looked into as well, though that will probably be further down the line

**Comment by alexandre-mbm** [comment]
Let me see if I understood. Currently the OAuth login does only access control to content private?

**Comment by Vivalldi** [comment]
As of right now that is correct

**Comment by alexandre-mbm** [comment]
**Hint:** full OAuth also for the admin plugin.
